### ISSUE TITLE
Sort by barcode returns KeyError after an hour

### ISSUE THREAD

**Issue by billytcl** [simoncchu/BarcodeMate#1]
I'm trying to use BarcodeMate for sorting a 10X linked reads bam file for use with xTea. It throws an error about an hour into the whole process.

My invocation command:

```
python /home/groups/hanleeji/BarcodeMate/x_toolbox.py -C -b 6382_9156_nb.phased_possorted_bam.bam -o 6382_9156_nb.phased_BCsorted_bam.bam -p ./tmp_sort -n 10
```

The error message:
```
Traceback (most recent call last):
  File "/home/groups/hanleeji/BarcodeMate/x_toolbox.py", line 85, in <module>
    xcvtr.cvt_bam_to_barcode_bam()
  File "/home/groups/hanleeji/BarcodeMate/x_converter.py", line 259, in cvt_bam_to_barcode_bam
    pool.map(unwrap_self_converter, zip([self] * len(l_chrm_records), l_chrm_records), 1)
  File "/home/groups/hanleeji/barcodemate_env/lib/python2.7/multiprocessing/pool.py", line 253, in map
    return self.map_async(func, iterable, chunksize).get()
  File "/home/groups/hanleeji/barcodemate_env/lib/python2.7/multiprocessing/pool.py", line 572, in get
    raise self._value
KeyError: 'CTGCGAGAGACATAAC_1'
Command exited with non-zero status 1
```

And inside the tmp_sort working folder:
```
total 57420480
-rw-r--r-- 1 billylau hanleeji 5153989685 Mar 15 15:58 6382_9156_nb.phased_possorted_bam.bam_chr1
-rw-r--r-- 1 billylau hanleeji 2905934550 Mar 15 15:44 6382_9156_nb.phased_possorted_bam.bam_chr10
-rw-r--r-- 1 billylau hanleeji 2616463236 Mar 15 15:58 6382_9156_nb.phased_possorted_bam.bam_chr11
-rw-r--r-- 1 billylau hanleeji 2706929825 Mar 15 16:01 6382_9156_nb.phased_possorted_bam.bam_chr12
-rw-r--r-- 1 billylau hanleeji 2070084077 Mar 15 15:57 6382_9156_nb.phased_possorted_bam.bam_chr13
-rw-r--r-- 1 billylau hanleeji 1757601582 Mar 15 15:57 6382_9156_nb.phased_possorted_bam.bam_chr14
-rw-r--r-- 1 billylau hanleeji 1661598505 Mar 15 15:57 6382_9156_nb.phased_possorted_bam.bam_chr15
-rw-r--r-- 1 billylau hanleeji 2319450112 Mar 15 16:02 6382_9156_nb.phased_possorted_bam.bam_chr16
-rw-r--r-- 1 billylau hanleeji 1897968316 Mar 15 16:01 6382_9156_nb.phased_possorted_bam.bam_chr17
-rw-r--r-- 1 billylau hanleeji 1615662437 Mar 15 16:02 6382_9156_nb.phased_possorted_bam.bam_chr18
-rw-r--r-- 1 billylau hanleeji  914358272 Mar 15 16:02 6382_9156_nb.phased_possorted_bam.bam_chr19
-rw-r--r-- 1 billylau hanleeji   38092169 Mar 15 16:01 6382_9156_nb.phased_possorted_bam.bam_chr1_KI270706v1_random
-rw-r--r-- 1 billylau hanleeji   34492560 Mar 15 16:01 6382_9156_nb.phased_possorted_bam.bam_chr1_KI270707v1_random
-rw-r--r-- 1 billylau hanleeji   35163943 Mar 15 16:01 6382_9156_nb.phased_possorted_bam.bam_chr1_KI270708v1_random
-rw-r--r-- 1 billylau hanleeji   98316706 Mar 15 16:02 6382_9156_nb.phased_possorted_bam.bam_chr1_KI270709v1_random
-rw-r--r-- 1 billylau hanleeji   34559919 Mar 15 16:02 6382_9156_nb.phased_possorted_bam.bam_chr1_KI270710v1_random
-rw-r--r-- 1 billylau hanleeji   36388007 Mar 15 16:02 6382_9156_nb.phased_possorted_bam.bam_chr1_KI270711v1_random
-rw-r--r-- 1 billylau hanleeji   39363925 Mar 15 16:02 6382_9156_nb.phased_possorted_bam.bam_chr1_KI270712v1_random
-rw-r--r-- 1 billylau hanleeji   34949695 Mar 15 16:02 6382_9156_nb.phased_possorted_bam.bam_chr1_KI270713v1_random
-rw-r--r-- 1 billylau hanleeji   34533764 Mar 15 16:02 6382_9156_nb.phased_possorted_bam.bam_chr1_KI270714v1_random
-rw-r--r-- 1 billylau hanleeji 5404047139 Mar 15 15:59 6382_9156_nb.phased_possorted_bam.bam_chr2
-rw-r--r-- 1 billylau hanleeji  864026624 Mar 15 16:02 6382_9156_nb.phased_possorted_bam.bam_chr20
-rw-r--r-- 1 billylau hanleeji  914358272 Mar 15 16:02 6382_9156_nb.phased_possorted_bam.bam_chr21
-rw-r--r-- 1 billylau hanleeji  767557632 Mar 15 16:02 6382_9156_nb.phased_possorted_bam.bam_chr22
-rw-r--r-- 1 billylau hanleeji   36473725 Mar 15 16:02 6382_9156_nb.phased_possorted_bam.bam_chr2_KI270715v1_random
-rw-r--r-- 1 billylau hanleeji   37026021 Mar 15 16:02 6382_9156_nb.phased_possorted_bam.bam_chr2_KI270716v1_random
-rw-r--r-- 1 billylau hanleeji 3750954845 Mar 15 15:50 6382_9156_nb.phased_possorted_bam.bam_chr3
-rw-r--r-- 1 billylau hanleeji   38728704 Mar 15 16:02 6382_9156_nb.phased_possorted_bam.bam_chr3_GL000221v1_random
-rw-r--r-- 1 billylau hanleeji 4128210224 Mar 15 15:52 6382_9156_nb.phased_possorted_bam.bam_chr4
-rw-r--r-- 1 billylau hanleeji   60387707 Mar 15 16:02 6382_9156_nb.phased_possorted_bam.bam_chr4_GL000008v2_random
-rw-r--r-- 1 billylau hanleeji 3584648888 Mar 15 15:49 6382_9156_nb.phased_possorted_bam.bam_chr5
-rw-r--r-- 1 billylau hanleeji   36518915 Mar 15 16:02 6382_9156_nb.phased_possorted_bam.bam_chr5_GL000208v1_random
-rw-r--r-- 1 billylau hanleeji 3250563961 Mar 15 15:47 6382_9156_nb.phased_possorted_bam.bam_chr6
-rw-r--r-- 1 billylau hanleeji 3298339522 Mar 15 15:46 6382_9156_nb.phased_possorted_bam.bam_chr7
-rw-r--r-- 1 billylau hanleeji 2839607375 Mar 15 15:44 6382_9156_nb.phased_possorted_bam.bam_chr8
-rw-r--r-- 1 billylau hanleeji 2559765840 Mar 15 15:42 6382_9156_nb.phased_possorted_bam.bam_chr9
-rw-r--r-- 1 billylau hanleeji   33554432 Mar 15 16:02 6382_9156_nb.phased_possorted_bam.bam_chr9_KI270717v1_random
-rw-r--r-- 1 billylau hanleeji   60706384 Mar 15 16:01 6382_9156_nb.phased_possorted_bam.bam_chrM
-rw-r--r-- 1 billylau hanleeji  675282944 Mar 15 16:02 6382_9156_nb.phased_possorted_bam.bam_chrX
-rw-r--r-- 1 billylau hanleeji  373331208 Mar 15 16:01 6382_9156_nb.phased_possorted_bam.bam_chrY
-rw-r--r-- 1 billylau hanleeji   78075044 Mar 15 16:03 merged_barcodes.txt
```

Edit: I looked inside merged_barcodes and I can find the barcode that it's throwing a KeyError on:
```
(/home/groups/hanleeji/barcodemate_env) [billylau@sh02-01n56 /scratch/groups/hanleeji/xtea/tmp_sort] (job 47299190) $ grep "CTGCGAGAGACATAAC_1" merged_barcodes.txt 
CTGCGAGAGACATAAC_1      2584377
```

**Comment by billytcl** [comment]
I figured this out -- it turns out that multiple runs cannot use the same working folder, as the merged_barcodes.txt is not unique across samples (as opposed to the other temporary files that it creates). I suggest that the developer(s) either make this really clear in the documentation (as in HPC scenarios we can queue up tons of these bam files) or create a unique file name for the merged_barcodes.txt.

**Comment by simoncchu** [comment]
Thank you for the suggestion!
